/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "embed_compiler_directives.h"
#include <stdint.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_feature_gate_carries_a_value_of_zero_or_one(void);
extern void test_the_static_assertion_compiles_at_file_and_block_scope(void);
extern void test_the_feature_tests_answer_zero_for_a_name_nothing_defines(void);
extern void test_the_endian_answer_agrees_with_the_bytes_of_a_word(void);
extern void test_the_argument_count_answers_the_length_of_the_list(void);
extern void test_the_paste_joins_a_name_to_an_expanded_count(void);
extern void test_the_call_passes_named_members_and_zeroes_the_rest(void);
extern void test_the_inline_and_flattened_helpers_run_their_bodies(void);
extern void test_a_packed_enum_takes_the_width_its_range_needs(void);
extern void test_the_alignment_attribute_raises_and_lowers(void);
extern void test_a_raw_word_reads_from_an_odd_address(void);
extern void test_the_diagnostic_bracket_bounds_a_suppression(void);
extern void test_the_weak_default_links_as_itself(void);
extern void test_the_declaration_guards_leave_a_c_declaration_intact(void);
extern void test_an_unreferenced_marked_definition_compiles_quietly(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/embedded_types/test/unit/test_embed_compiler_directives\\test_embed_compiler_directives.c");
  run_test(test_every_feature_gate_carries_a_value_of_zero_or_one, "test_every_feature_gate_carries_a_value_of_zero_or_one", 243);
  run_test(test_the_static_assertion_compiles_at_file_and_block_scope, "test_the_static_assertion_compiles_at_file_and_block_scope", 260);
  run_test(test_the_feature_tests_answer_zero_for_a_name_nothing_defines, "test_the_feature_tests_answer_zero_for_a_name_nothing_defines", 277);
  run_test(test_the_endian_answer_agrees_with_the_bytes_of_a_word, "test_the_endian_answer_agrees_with_the_bytes_of_a_word", 294);
  run_test(test_the_argument_count_answers_the_length_of_the_list, "test_the_argument_count_answers_the_length_of_the_list", 322);
  run_test(test_the_paste_joins_a_name_to_an_expanded_count, "test_the_paste_joins_a_name_to_an_expanded_count", 341);
  run_test(test_the_call_passes_named_members_and_zeroes_the_rest, "test_the_call_passes_named_members_and_zeroes_the_rest", 354);
  run_test(test_the_inline_and_flattened_helpers_run_their_bodies, "test_the_inline_and_flattened_helpers_run_their_bodies", 373);
  run_test(test_a_packed_enum_takes_the_width_its_range_needs, "test_a_packed_enum_takes_the_width_its_range_needs", 386);
  run_test(test_the_alignment_attribute_raises_and_lowers, "test_the_alignment_attribute_raises_and_lowers", 403);
  run_test(test_a_raw_word_reads_from_an_odd_address, "test_a_raw_word_reads_from_an_odd_address", 422);
  run_test(test_the_diagnostic_bracket_bounds_a_suppression, "test_the_diagnostic_bracket_bounds_a_suppression", 449);
  run_test(test_the_weak_default_links_as_itself, "test_the_weak_default_links_as_itself", 474);
  run_test(test_the_declaration_guards_leave_a_c_declaration_intact, "test_the_declaration_guards_leave_a_c_declaration_intact", 486);
  run_test(test_an_unreferenced_marked_definition_compiles_quietly, "test_an_unreferenced_marked_definition_compiles_quietly", 498);

  return UNITY_END();
}
