sonar.projectKey=dstroy0_embedded_types
sonar.organization=dstroy0

sonar.projectName=embedded_types
sonar.projectVersion=1.0.0

sonar.sources=include
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,build-*/**

sonar.test.exclusions=test/**/unity_runner.c

sonar.coverage.exclusions=test/**

sonar.cfamily.compile-commands=bw-output/compile_commands.json
