/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "embed_dispatch_layout.h"
#include "embed_types.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_argument_count_answers_the_length_of_the_list(void);
extern void test_the_paste_joins_a_name_to_an_expanded_count(void);
extern void test_the_call_passes_named_members_and_zeroes_the_rest(void);
extern void test_each_member_reaches_the_function_it_names(void);
extern void test_the_table_is_exactly_its_three_pointers(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/embedded_types/test/unit/test_embed_dispatch_layout\\test_embed_dispatch_layout.c");
  run_test(test_the_argument_count_answers_the_length_of_the_list, "test_the_argument_count_answers_the_length_of_the_list", 51);
  run_test(test_the_paste_joins_a_name_to_an_expanded_count, "test_the_paste_joins_a_name_to_an_expanded_count", 72);
  run_test(test_the_call_passes_named_members_and_zeroes_the_rest, "test_the_call_passes_named_members_and_zeroes_the_rest", 105);
  run_test(test_each_member_reaches_the_function_it_names, "test_each_member_reaches_the_function_it_names", 167);
  run_test(test_the_table_is_exactly_its_three_pointers, "test_the_table_is_exactly_its_three_pointers", 183);

  return UNITY_END();
}
