/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "embed_types.h"
#include <stdint.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_widths_are_the_widths_they_are_named_for(void);
extern void test_the_signed_aliases_carry_a_sign_and_the_unsigned_ones_do_not(void);
extern void test_the_word_matches_the_pointer_it_was_derived_from(void);
extern void test_the_index_fits_the_register_and_is_two_or_four_bytes(void);
extern void test_the_boolean_normalizes_every_nonzero_to_one(void);
extern void test_a_raw_word_reads_from_an_odd_address(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/embedded_types/test/unit/test_embed_types\\test_embed_types.c");
  run_test(test_the_widths_are_the_widths_they_are_named_for, "test_the_widths_are_the_widths_they_are_named_for", 49);
  run_test(test_the_signed_aliases_carry_a_sign_and_the_unsigned_ones_do_not, "test_the_signed_aliases_carry_a_sign_and_the_unsigned_ones_do_not", 67);
  run_test(test_the_word_matches_the_pointer_it_was_derived_from, "test_the_word_matches_the_pointer_it_was_derived_from", 89);
  run_test(test_the_index_fits_the_register_and_is_two_or_four_bytes, "test_the_index_fits_the_register_and_is_two_or_four_bytes", 107);
  run_test(test_the_boolean_normalizes_every_nonzero_to_one, "test_the_boolean_normalizes_every_nonzero_to_one", 122);
  run_test(test_a_raw_word_reads_from_an_odd_address, "test_a_raw_word_reads_from_an_odd_address", 149);

  return UNITY_END();
}
