# embedded_types - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational

add_subdirectory(test_embed_compiler_directives)
add_subdirectory(test_embed_dispatch_layout)
add_subdirectory(test_embed_types)
